sudo: false

language: java

jdk: openjdk8

env:
  global:
    - LANG="ja_JP.utf8" _JAVA_OPTIONS="-Duser.language=ja -Duser.country=JP"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-ja
  - sudo /etc/init.d/mysql stop
  - docker-compose -f docker/docker-compose.yml up -d

script:
  - ./gradlew clean :sample-web-admin:build
  - cp sample-web-admin/build/libs/sample-web-admin.jar docker/image/api
  - docker build -t mirrored1976/sample-api docker/image/api
  - docker build -t mirrored1976/sample-db docker/image/db

after_script:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push mirrored1976/sample-api
  - docker push mirrored1976/sample-db
