version: '2'
services:
    mysql:
        build: ./mysql
        container_name: mysql
        environment:
            - MYSQL_DATABASE=sample
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=passw0rd
            - TZ=Japan
        ports:
            - "3306:3306"
